AWSTemplateFormatVersion: "2010-09-09"
Description: "ASG con Launch Template y UserData simple, asociado a ALB"

Parameters:

  Environment:
    Type: String
    Default: dev

  AmiId:
    Type: AWS::EC2::Image::Id

  InstanceType:
    Type: String
    Default: t3.micro

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: aws-platform-key

  SecurityGroupEc2:
    Type: AWS::EC2::SecurityGroup::Id
    Description: SG del ALB (se usará como origen para tráfico HTTP)

  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id

  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id

  TargetGroupArn:
    Type: String
    Description: Target Group ARN creado en alb.yaml

  VpcId:
    Type: AWS::EC2::VPC::Id


Resources:

  AsgSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG para instancias del ASG
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        # HTTP desde el ALB
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref SecurityGroupEc2
        # SSH desde toda la VPC (incluye Bastion)
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-asg-sg"

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref AsgSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y nginx
            systemctl enable nginx
            systemctl start nginx

            echo "<h1>ASG - ${Environment} - Instancia OK</h1>" > /usr/share/nginx/html/index.html

        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Environment
                Value: !Ref Environment
              - Key: Name
                Value: !Sub "${Environment}-asg-instance"
                

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: "2"
      MaxSize: "4"
      DesiredCapacity: "2"
      TargetGroupARNs:
        - !Ref TargetGroupArn
      HealthCheckType: ELB
      HealthCheckGracePeriod: 60
      Tags:
        - Key: Environment
          Value: !Ref Environment
          PropagateAtLaunch: true
        - Key: Name
          Value: !Sub "${Environment}-asg"
          PropagateAtLaunch: true


Outputs:

  ASGName:
    Value: !Ref AutoScalingGroup

  LaunchTemplateId:
    Value: !Ref LaunchTemplate

  AsgSecurityGroupId:
    Value: !Ref AsgSecurityGroup
