AWSTemplateFormatVersion: "2010-09-09"
Description: "VPC Endpoints - S3, DynamoDB y SSM (interface)"


Parameters:
  Environment:
    Type: String
    Default: dev

  VpcId:
    Type: AWS::EC2::VPC::Id

  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id

  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

  PrivateRouteTableId:
    Type: String
    AllowedPattern: "^rtb-[a-zA-Z0-9]+$"
    Description: Route Table privado compartido (priv-subnets)

Resources:

  VPCEndpointS3:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Gateway
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      VpcId: !Ref VpcId
      RouteTableIds:
        - !Ref PrivateRouteTableId

  VPCEndpointDDB:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Gateway
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.dynamodb"
      VpcId: !Ref VpcId
      RouteTableIds:
        - !Ref PrivateRouteTableId

  VPCEndpointSSM:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ssm"
      VpcId: !Ref VpcId
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecurityGroupId
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
